// Generated by git-typstdiff HEAD~3...HEAD on test.typ

#let insert(x) = highlight(fill: green, x)
#let delete(x) = strike(stroke: 1.5pt + red, x)

= This is a header

#insert[]
#insert[== Add something]
#insert[]
#insert[Description!]
